### ISSUE TITLE
Scrolling on mobile view

### ISSUE THREAD

**Issue by hereisamin** [inertiajs/pingcrm#101]
on organizations and contact pages for mobile view (screen-wide < 750) console shows this error while scrolling down or up:

index.js:1 Uncaught TypeError: t.target.hasAttribute is not a function
    at Object.handleScrollEvent (index.js:1)
    at index.js:1

<img width="1229" alt="Screen Shot 1399-10-14 at 17 26 38" src="https://user-images.githubusercontent.com/3470922/103480362-29dcff80-4de9-11eb-89c9-0e6e06fc9c0d.png">

**Comment by reinink** [comment]
Thanks for reporting, but I can't reproduce this on the latest version (#99), so I suspect this might be fixed. Please report back if otherwise.
