### ISSUE TITLE
Flash message re-appears on page navigation

### ISSUE THREAD

**Issue by iamniels** [inertiajs/pingcrm#102]
When a flash message is closed by the user, it will re-appear when the user navigates back to the page.

How to reproduce:
- Enter a form & submit
- You will be navigated to a page with a success flash message
- Close the flash message
- Navigate back to the form and then navigate forward to the page again
- The flash message is displayed again

Especially when flash messages appear with some animation, this is troublesome, because to the user it appears that the message is a result to something he just did.

**Comment by iamniels** [comment]
Any ideas for an approach?

One idea is to add unique identifiers to the messages and to store in the browser's local storage whether a message has been displayed already or not. But this seems overly complicated to me.

**Comment by reinink** [comment]
This is expected behaviour with Inertia.js. The flash message is sent from the server as a prop, and props are saved in history. This is desirable, and follows standard browser behaviour, where navigating through history shows the page exactly as it was when navigated away from.
