### ISSUE TITLE
Sharing data in $page

### ISSUE THREAD

**Issue by shineability** [inertiajs/pingcrm#103]
Reading through the Inertia docs and exploring this demo...

Couldn't help but noticing that in e.g. [**Layout.vue**](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/Layout.vue), shared data is accessed as `$page.auth.user` instead of `$page.props.auth.user` (as described in the current docs).

- Is this a change in the newer version?
- Also, isn't this more prone to errors because you can overwrite props from the actual page?

Probably missing something :)

**Comment by zappzerapp** [comment]
The documentary refers to the latest version of Inertia. Have a look at the [upgrade branch](https://github.com/inertiajs/pingcrm/tree/upgrade)

**Comment by reinink** [comment]
Yup, this is fixed in #99, which I hope to merge in soon. 👍
