### ISSUE TITLE
Pagination breaks when Model Caching is enabled (GeneaLabs/laravel-model-caching)

### ISSUE THREAD

**Issue by jjsavrx** [inertiajs/pingcrm#105]
Hello,

I am using pingcrm to test numerous features for an upcoming project that I wish to build within the framework. I am experiencing a unique issue with pagination throwing an error, specifically when I pair a model with the Caching package "GeneaLabs/laravel-model-caching". I have used the caching package outside of the Inertia framework and it works great, however within the framework it has issues. Models by themselves still work great within Inertia with the Caching package enabled (via "use Cachable" declared in the Model's PHP file), however when a model is invoked via Laravel's Eloquent ORM with pagination, I receive the following error: "Serialization of 'class@anonymous' is not allowed", which from what I could gather is tied directly to the framework's code in the file "app/Providers/AppServiceProvider.php" for the "protected function registerLengthAwarePaginator()". I believe because the function uses the line "return new class (...array_values($values)) extends LengthAwarePaginator", it creates an anonymous class which causes the caching to break.

The method in which I am using to test this is adding both "use GeneaLabs\LaravelModelCaching\Traits\Cachable;" (file header) and "use Cachable" (inside the model) to the "Contact" model (in the file "app/Models/Contact.php"). When I access the page "/contacts" I receive the error.

I have also been able to successfully create a LengthAwarePaginator via cached data (directly via Illuminate\Pagination\LengthAwarePaginator), however due to it not being created by the function declared in "AppServiceProvider.php", the front-end does not correctly load the data.

Again this is a unique issue tied to a completely separate Laravel package (GeneaLabs/laravel-model-caching), but ultimately it would be wonderful if they could work in unison.

Please advise. Thank you!

**Comment by reinink** [comment]
The `LengthAwarePaginator` hack has been removed in the latest update: #99. This is possible given the (somewhat recent) paginator improvements in Laravel core. 👍
