### ISSUE TITLE
Code reuse for edit/create contact page

### ISSUE THREAD

**Issue by ossicoinc** [inertiajs/pingcrm#106]
I'd say it's poor form (pun intended) to copy and paste the form portion between the edit and create views. I went to this demo page to see how one would reuse a template like that and was disappointed that it doesn't, even though it's exactly the same form. If you add a field you'd have to update both.

**Comment by reinink** [comment]
So I kind of disagree that duplicating code between the create and edit forms is bad design. In my experience building real apps, rarely are the create and edit forms identical...even if they are in this particular demo app. As a rule, I think a little duplication here is better than trying to find an abstraction that might get in the way in the future.
