### ISSUE TITLE
How to put it into production?

### ISSUE THREAD

**Issue by carlosalbertocruz** [inertiajs/pingcrm#108]
After using the npm production command and generating the files, I uploaded it to the host only that I get this error:

===
app.js:157943 [Vue warn]: Error in render: "TypeError: Cannot read property 'dataset' of null"

(found in <Root>)

===

app.js:157943 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getAttribute' of undefined"

(found in <Root>)

Ps: on local is working properly

**Comment by reinink** [comment]
Hmm, I am not able to reproduce this, at least not on the latest version (#99). I'd recommend doing the classic delete node_modules folder trick, and reinstalling. 👍 

Also, this makes me wonder if you're maybe using an older version of Node on your server? 🤔
