### ISSUE TITLE
Serialization of 'Illuminate\Http\UploadedFile' is not allowed 

### ISSUE THREAD

**Issue by mrengineer19** [inertiajs/pingcrm#110]
Hello,

I'm trying to upload file but getting `Serialization of 'Illuminate\Http\UploadedFile' is not allowed` error. One thing I'm using is form request instead of direct validation. This error comes when I upload image and keep required fields null then 

Please suggest some way so that I can use form request and upload an image file.

**Comment by reinink** [comment]
Hmm, I'm not able to reproduce this, and this doesn't sound like an issue with Ping CRM directly. Are you maybe trying to do something [like this](https://stackoverflow.com/questions/40552818/laravel-queue-error-serialization-of-illuminate-http-uploadedfile-is-not-allow)?

Either way, closing this for now. If you can give me steps how to reproduce this in Ping CRM, I'd be happy to reopen. 👍
