### ISSUE TITLE
Pagination, i.default is not a function

### ISSUE THREAD

**Issue by meatjasenmp** [inertiajs/pingcrm#116]
Hi, I'm getting a strange error when attempting to implement pagination in a Laravel/Interia setup. The key difference between the pingcrm demo and my app is that I'm using "@inertiajs/inertia-vue3": "^0.3.5". It works fine if I use standard links but the following

`<template v-for="link in links">
				<div v-if="link.url === null" class="mr-1 mb-1 px-4 py-3 text-sm leading-4 text-gray-400 border rounded" v-html="link.label" />
				<a v-else v-html="link.label" :href=link.url />
				<inertia-link v-else
		              class="mr-1 mb-1 px-4 py-3 text-sm leading-4 border rounded hover:bg-white focus:border-indigo-500 focus:text-indigo-500"
		              :class="{ 'bg-white': link.active }" :href="link.url" v-html="link.label" />
			</template>`

Is throwing a Uncaught (in promise) TypeError: i.default is not a function error.

The controller I'm using for reference:

` $categories = DB::table('categories')->latest()->paginate(5);

        return Inertia::render('Admin/Categories/Index', [
            'categories' => $categories
        ]);`

**Comment by meatjasenmp** [comment]
I believe I found my answer in the vue3 hacking branch. Fingers crossed.

**Comment by peckanthony** [comment]
Had the same issue just now, fixed it by removing v-html and using the closing tag

`<inertia-link v-else class="mr-1 mb-1 px-4 py-3 text-sm leading-4 border rounded hover:bg-white focus:border-indigo-500 focus:text-indigo-500"
                              :href="link.url">
                    {{ link.label }}
                </inertia-link>`

**Comment by meatjasenmp** [comment]
> Had the same issue just now, fixed it by removing v-html and using the closing tag
> 
> `<inertia-link v-else class="mr-1 mb-1 px-4 py-3 text-sm leading-4 border rounded hover:bg-white focus:border-indigo-500 focus:text-indigo-500" :href="link.url"> {{ link.label }} </inertia-link>`

Thanks! I'll try it tonight.

**Comment by peckanthony** [comment]
The `{{ link.label }}` escapes your characters, so for the << prev and next >> buttons, I had to put that in a span inside the inetia-link
`<span v-html="link.label"></span>`

**Comment by ed-mor** [comment]
Yo di con esta solución (  v-html="link.label" ), ya que mostraba: &raquo; &laquo;

**Comment by reinink** [comment]
This isn't a Ping CRM issue, and it sounds solved either way, so I'm closing this. 👍
