### ISSUE TITLE
session table migration is missing

### ISSUE THREAD

**Issue by Sairahcaz** [inertiajs/pingcrm#117]
I followed the README installation steps.
And opened localhost:8000 and I get the message session table does not exists.
I added the session table migration from another project and it worked.

So just adding the session table migration to the repo would fix the bug!

**Comment by iammikek** [comment]
you should have `SESSION_DRIVER=file` if you've copied the `.env.example'

this should require a session table. Whats your SESSION_DRIVER set to?

**Comment by Sairahcaz** [comment]
I guess I did not had sqlite and just used a db config from another project .env-file. There the session driver was database and the DB was set to mysql...

**Comment by reinink** [comment]
You shouldn't need a session table, since the default session driver is set to `file`, and that should be sufficient.

https://github.com/inertiajs/pingcrm/blob/cb723eeaee94a6c9031e887f0fc31d46a4fd5976/.env.example#L14
