### ISSUE TITLE
"Inertia.replace() has been deprecated and will be removed in a future release." warning

### ISSUE THREAD

**Issue by nioperas06** [inertiajs/pingcrm#119]
Hi all,

This line `this.$inertia.replace(this.route('organizations', Object.keys(query).length ? query : { remember: 'forget' }))` [link](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Organizations/Index.vue#L90) actually throws this warning :

`Inertia.replace() has been deprecated and will be removed in a future release. Please use Inertia.get() instead`. Once  replaced as suggested, the form input loses focus as you type. A workaround?

**Comment by BSKnuckles** [comment]
> `Inertia.replace() has been deprecated and will be removed in a future release. Please use Inertia.get() instead`. Once replaced as suggested, the form input loses focus as you type. A workaround?

Jeffrey shows how to fix this on [Laracasts](https://laracasts.com/series/learn-inertia-with-jeffrey/episodes/10)

The short answer is to change it to:

`this.$inertia.get(this.route('contacts', Object.keys(query).length ? query : {remember: 'forget' }), {}, { preserveState: true })`

**Comment by nioperas06** [comment]
Thank you @BSKnuckles

**Comment by philharmonie** [comment]
`replace()` keeps the focus in an input and `get()` does not. What's the workaround for that?
