### ISSUE TITLE
Sidebar menu with treeview

### ISSUE THREAD

**Issue by unknown-coder-1** [inertiajs/pingcrm#125]
I would like to add a sidebar menu "treeview" option which works properly after login. Does anyone have tried it before? If yes then how can we do it? Thank you.

**Comment by unknown-coder-1** [comment]
@nicerazer yeah unfortunately seems so as we don't get any answer for our current question. Dynamic sidebar menu with treeview currently not supported by pinc crm.

**Comment by reinink** [comment]
Hey thanks for your interest in Inertia.js! 👍

So, Ping CRM is intended to be a simple demo app, to help illustrate the core concepts of Inertia. It isn't meant to provide examples of how to do everything possible within an Inertia app.

These are great questions for our [Discord channel](https://discord.gg/inertiajs), or our [discussions section](https://github.com/inertiajs/inertia/discussions) on GitHub. 

Good luck!
