### ISSUE TITLE
ziggy route().current() for active url indicator

### ISSUE THREAD

**Issue by MartinP7r** [inertiajs/pingcrm#141]
First off, thank you for providing this sample project! 

I'm currently implementing my project with vue3 and inertia while referencing your `vue3-hacking` branch and was curious about your `isUrl` implementation to indicate the currently active route.

I was wondering if you have an idea why ziggy's `route().current()` doesn't seem to work correctly in this case?

Also, 

https://github.com/tighten/ziggy/issues/367#issuecomment-731700358

seems like a nice solution that I'm currently using. Could you have a look at it and maybe share your thoughts about possible caveats?

**Comment by claudiodekker** [comment]
Hey @MartinP7r,

I'm not sure why Ziggy wouldn't work with it, but then again, we actually already stopped using Ziggy ourselves. Instead, we now use template literals like these:

```js
// Compact; we use this one the most
:href="`/users/${user.id}/edit`"

// As an alternative, you could do this, which makes it easy to search-and-replace all references
:href="'/users/:user/edit'.replace(':user', user.id)"
```

In part, we started using these to avoid weird issues with Ziggy's objects, and in part to remove a package that adds a lot of (what I would call) bloat while only providing a small bit of convenience (try viewing your page source, way over half of the content there is Ziggy dumping the routes and attaching itself to the window).

Anyway, I'm not saying you shouldn't use Ziggy (if you like it, by all means keep using it!), but I just wanted to mention that this is how we tend to approach Route-related things & how we will going forward.

**Comment by claudiodekker** [comment]
As for my thoughts on that solution; it's not bad, but there isn't really a need to share the current route name. 

Instead, you can simply use the Page component or URL instead, which [are already being transmitted each time a page is loaded](https://inertiajs.com/the-protocol#the-page-object).

For example, you could do something like this to indicate an active URL:
```html
<Link :href="`/servers/${server.id}/keys`" :class="{ 'link-active-class': $page.component === 'Servers/Keys' }">
  Server Keys
</Link>
```

Alternatively, you can indeed do something similar to our `isUrl` helper:
```js
<div :class="{ 'active-class': activeItem === 'sites' }">Sites</div>

// ...

computed: {
    activeItem() {
       if (this.$page.url.startsWith('/servers') && !this.$page.url.includes('/sites/')) {
        return 'servers'
      } else {
        return 'sites'
      }
    },
  },
```

I hope this explains.
