### ISSUE TITLE
scroll-region is not working

### ISSUE THREAD

**Issue by saeedvaziry** [inertiajs/pingcrm#142]
In my case the `scroll-region` is not working and it is resetting the scroll position to the top on every peage load

    <div class="h-40 overflow-y-auto p-3" scroll-region>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
        <inertia-link href="..." preserve-scroll>Link</inertia-link>
    </div>

**Comment by reinink** [comment]
Are you using Ping CRM and scroll regions are not working? Issues in this repo should be kept to issues related to Ping CRM. I just tested this, and it seems to be working fine.

If you're having issues in your own app, I'd recommend asking this in our [GitHub discussions](https://github.com/inertiajs/inertia/discussions), or in our [Discord channel](https://discord.gg/inertiajs). 👍
