### ISSUE TITLE
Error in created hook: "TypeError: Cannot read property 'version' of undefined"

### ISSUE THREAD

**Issue by cloudstudio** [inertiajs/pingcrm#15]
Hello !! I follow all instructions ( nothing hard ) and all right!

When I go to /login i get this error.

![Captura de pantalla 2019-04-18 a las 9 03 37](https://user-images.githubusercontent.com/3589377/56342728-18893500-61b9-11e9-813b-4cdc3c2222ce.png)

Something that can be?  Thanks !!!!

**Comment by reinink** [comment]
Try again, I made a bunch of changes to Inertia yesterday that caused this. I've just updated this repo to match those changes. 🤟

**Comment by cloudstudio** [comment]
@reinink  I update all, and recompile and I get 

Undefined variable: component  in app.blade.php

Thanks for you time !

**Comment by reinink** [comment]
Have you cleared your view cache? Try this:

```sh
php artisan view:clear
```

**Comment by cloudstudio** [comment]
I did not, what a shame :/

Working now, thanks

**Comment by reinink** [comment]
👍
