### ISSUE TITLE
Javascript error while adding photo: TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by lalitj** [inertiajs/pingcrm#150]
On uploading a new profile photo on the user edit page, the page is stuck and the following JS error is seen in the console.

![image](https://user-images.githubusercontent.com/990271/124387173-16a8df00-dcfb-11eb-95cd-4572af7624cd.png)

**Comment by lalitj** [comment]
@reinink Can you please have a look at this issue?

**Comment by ariadys** [comment]
same error...

**Comment by barnoma-soz** [comment]
Perhaps this will help, but it works like this for me:

```php
update() {
  this.form.post(this.route('users.update', this.user.id).url(), {
    onSuccess: () => this.form.reset('password', 'photo'),
  })
},
```

**Comment by tkuijer** [comment]
Can confirm this issue exists, only occurs when uploading a file using the form. Changing the form method from post to put doesn't make a difference.

**Comment by MichaelJob** [comment]
Thanks to @barnoma-soz - adding the ".url()" helped. Thanks

> Perhaps this will help, but it works like this for me:
> 
> ```
> // in resources/js/Pages/Users/Edit.vue
> update() {
>   this.form.post(this.route('users.update', this.user.id).url(), {
>     onSuccess: () => this.form.reset('password', 'photo'),
>   })
> },
> ```
