### ISSUE TITLE
Vue3: inertia link not working

### ISSUE THREAD

**Issue by SaeedSoltoon** [inertiajs/pingcrm#164]
Hi, Jonathan.
First of all, I want to thank you for this great work, and please keet it up.

I just switch to vue3-hacking branch to test vue3 in order to have the ability use element-plus and other vue3 compatible libs, and pass the installation issues and resolve them for both composer and npm, everything is ok and build successfully.

But when I serve the project using artisan serve I have a warning in console.
`Failed to resolve component: inertia-link`
and all links are not working, and remain as <inertia-link... /> and not converted to anchor tags.

Do you have any advice for me? Or I have to stick to vue2 version?

**Comment by hendrikhaack** [comment]
Did you import and register the `<InertiaLink>` component locally or globally by yourself?
Because in [#765](https://github.com/inertiajs/inertia/pull/765) the global component registration was removed from the Vue 2 and Vue 3 adapters.

**Comment by SaeedSoltoon** [comment]
Thanks @hendrikhaack. My issue has been resolved.
