### ISSUE TITLE
Vue3: Dropdown addEventListener keydown not removed on unmount

### ISSUE THREAD

**Issue by jrson83** [inertiajs/pingcrm#168]
Hey,
the `document.addEventListener('keydown' ...` in Dropdown.vue does not get removed on component `unmount`, so it gets repeatedly added to the document EventListeners on page change.

![2022-01-03_08h32_34](https://user-images.githubusercontent.com/45284565/147907835-81a6a666-4bc7-434d-b236-d3890dea4da7.png)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
