### ISSUE TITLE
Feature request: Update project to Vue3 + Composition API

### ISSUE THREAD

**Issue by ericmp33** [inertiajs/pingcrm#174]
Would be nice to see how this project would look like using Vue3 + Composition API. I guess in a future will be updated.

**Comment by mchev** [comment]
#175

**Comment by driesvints** [comment]
It's highly unlikely we'll ever do this sorry.

**Comment by reinink** [comment]
Hey! Just chatting with @driesvints about this and we actually think we might eventually do this, but if we do it's something that I want to handle personally 👍

**Comment by driesvints** [comment]
Going to re-open and pin this one.

**Comment by JackEllis** [comment]
Just adding my two cents to say I'm still not fully sold on composition API being the "new" way, just "A" way. But also here to say that I'd be curious to see a version from @reinink ;)

**Comment by LouiScura** [comment]
Would be great to leave the options API but also add the compositions API.  Have both versions for people to choose.
