### ISSUE TITLE
error compiling assets with npm run watch

### ISSUE THREAD

**Issue by sbaum2s** [inertiajs/pingcrm#180]
Issue has gone

**Comment by ordago** [comment]
The `@` is an alias. The config is here:

https://github.com/inertiajs/pingcrm/blob/b1eb5b0587f01b9d9a7b2b17f2bde4d9132ee8ba/webpack.config.js#L8

**Comment by sbaum2s** [comment]
The config file is correct. So, still no progress in solving this.

**Comment by sbaum2s** [comment]
Lost in complexity of steps
