### ISSUE TITLE
Popper: Invalid reference or popper argument provided

### ISSUE THREAD

**Issue by umarfarooqumzen** [inertiajs/pingcrm#192]
I copied the same code and i am getting  this error when i click on the filter dropdown. I have tried everything in my power but it is weird I am facing this issue
I am using Laravel + with inertia js everything is latest. I copied the search filter file, dropdown file and etc, data is loading ok and the search filter is also ok but i am not able to run this filter dropdown becuase  of this console error
createPopper.js:209 Popper: Invalid reference or popper argument provided. They must be either a DOM element or virtual element.

![image](https://user-images.githubusercontent.com/49918854/213786183-51a848f5-fb16-4bf1-b8fe-6e6a92621779.png)

![image](https://user-images.githubusercontent.com/49918854/213786280-f4a4f065-c9d3-46fa-b44b-5c9daa6b0ba4.png)

**Comment by RyanGSampson** [comment]
I also am facing the same issue. Any suggestions would be thanked.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
