### ISSUE TITLE
Are you planning to update to inertia V1.0?

### ISSUE THREAD

**Issue by mauthi** [inertiajs/pingcrm#193]

**Comment by n4j1Br4ch1D** [comment]
https://discord.com/channels/592327939920494592/592327939920494594/1063848453052051456
me: "so cool: would Pingcrm (vue,svelte) be updated soon?"
reinink responded : "yup, that's the plan 👍"

**Comment by hurycz** [comment]
+1

**Comment by zajinx** [comment]
+1

**Comment by clickervinod** [comment]
> https://discord.com/channels/592327939920494592/592327939920494594/1063848453052051456 me: "so cool: would Pingcrm (vue,svelte) be updated soon?" reinink responded : "yup, that's the plan 👍"

also include react in plan.  Thanks

**Comment by jessarcher** [comment]
Updated in #209
