### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by devnll** [inertiajs/pingcrm#195]
Not sure if this is intentional but figured I'd report it just in case, as it feels somewhat counterintuitive.

As an example, there are several contacts with "Bar" in their names (Ceasar Barrows, Margot Bartoletti), and when I type "Bar" they are found, however entering "bar" yields an empty list. This caught me off guard when I first tried the demo, but maybe it's a feature and not a bug? ;)

(loooove Inertia btw, thanks so much for all your work on it!)

**Comment by ntaylor-86** [comment]
@devnll  are you using the default Sqlite database for this project?

```
DB_CONNECTION=sqlite
```

Sqlite __IS__ case-sensitive.

**Comment by devnll** [comment]
Sorry, I should have specified. I was referring to the existing online demo referenced in the repo's About section:
http://demo.inertiajs.com/

**Comment by driesvints** [comment]
We use postgresql which is case sensitive unfortunately. But this isn't a major concern for the purpose of this demo app really. It's really about showcasing how you can build an app with Inertia. Thanks for mentioning though!
