### ISSUE TITLE
Feature Request : Modals Classes Prop Merge

### ISSUE THREAD

**Issue by prezire** [inertiajs/pingcrm#196]
It would be nice to have a mergeable classes prop for both Modal and ConfirmationModal. I was thinking of having something like this to align them vertically, for example:
```html
<Modal classes="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" :show="showModal" @close="showModal = false">
    <div class="p-3">
      Hello World
    </div>
</Modal>
 ```
Please let me know if there's a better way to do this.

**Comment by driesvints** [comment]
Might be better to open up an idea on the discussions tab of https://github.com/inertiajs/inertia/discussions
