### ISSUE TITLE
CSS not loaded with non https url

### ISSUE THREAD

**Issue by Rattone** [inertiajs/pingcrm#202]
There is a problem with loading app.css with http address on Chrome and other browsers which prevents stylesheets from insecure address on https pages. There is already a [PR that solves this problem](https://github.com/inertiajs/pingcrm/pull/194) but I believe the problem is the APP_URL in the env file...

![image](https://github.com/inertiajs/pingcrm/assets/7362607/66cff278-6875-4c7e-9667-22d3bf7fb95b)

**Comment by driesvints** [comment]
It's fixed. Thanks
