### ISSUE TITLE
How do install Inertia in laravel app starting fresh project, 

### ISSUE THREAD

**Issue by JayJay-101** [inertiajs/pingcrm#210]

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JayJay-101** [comment]
i am using breeze install for inertia setup in laravel (SSR),  what version from there i need to install inertia so that it runs only from php artisan serve, 
i am able to render  the vue templates from laravel controller but the issue is i have to  maintain two terminal running constantly for
php artisan serve
and
npm run dev

but in the demo project thats not the case, only php artisan serve sufffice the render
