### ISSUE TITLE
Axios XSRF Vulnerability

### ISSUE THREAD

**Issue by RyanGSampson** [inertiajs/pingcrm#214]
Please update axios version.

#  npm audit report

axios  0.8.1 - 0.27.2
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/@inertiajs/inertia/node_modules/axios
  @inertiajs/inertia  *
  Depends on vulnerable versions of axios
  node_modules/@inertiajs/inertia
    @inertiajs/inertia-vue3  *
    Depends on vulnerable versions of @inertiajs/inertia
    node_modules/@inertiajs/inertia-vue3

**Comment by driesvints** [comment]
This repo shouldn't be affected but appreciate your report 👍
