### ISSUE TITLE
Question - How to correctly migrate to mysql

### ISSUE THREAD

**Issue by marmz** [inertiajs/pingcrm#216]
Trying to export sqlite database and import to mysql, then change the driver.
But having trouble with import staatement wich returns this error:

Syntax error near 'PRAGMA foreign_keys=OFF' row 1

Can you show the right way to migrate pingcrm to mysql-server?
Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
