### ISSUE TITLE
Login pending...

### ISSUE THREAD

**Issue by rust-x** [inertiajs/pingcrm#23]
So I tried to clone the repo, did all the necessary steps, but when I type the credentials (johndoe@example.com / secret) the login button keeps turning. and I can't pass the login formular.

**Comment by reinink** [comment]
Sorry @rust-x, not sure what's wrong without more info. I just tried again following the instructions in the readme, and it work without issue.

Can you try login again, and see if you're getting an error in the console?

**Comment by reinink** [comment]
Closing this because I don't think it's a bug with the library. However, feel free to post more info, and I'll be happy to work through this with you. 🤟

**Comment by rust-x** [comment]
Well, here are the error I get when I try to login 
<img width="1145" alt="Screenshot 2019-05-22 at 20 27 47" src="https://user-images.githubusercontent.com/10800660/58199134-1f332c80-7cd0-11e9-9b8b-e74c4b4fbf63.png">
