### ISSUE TITLE
clear password field on validation failure

### ISSUE THREAD

**Issue by ivalkenburg** [inertiajs/pingcrm#26]
How would you go about clearing a field after lets say a validation error, for example clearing the password field after wrong password is given at login. $inertia.post promise resolves before the props are set so I cant act on that.

**Comment by reinink** [comment]
Hmm, I haven't really run into a use-case where I've needed this. I never clear the password on login failure. That said, one way to solve this is with a watcher:

```js
watch: {
  '$page.errors'(errors) {
    if (Object.keys(errors).length) {
      this.form.password = ''
    }
  },
},
```

As a general rule it's best not to think of an Inertia visit as an XHR request, where you do something when it's completed. Rather, it's better to think of it as a normal server-side form submission. If you want to change something client-side based on that request, the idiomatic way to do this would be to pass some type of prop from the server for this.

That said, if you did want fine-grain control like this, you could always make your login request manually over XHR (ie. with Axios). It just means a little more work.

Hope that helps!

//cc @sebastiandedeyne Curious if you have any thoughts on this.
