### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by ManojKiranA** [inertiajs/pingcrm#27]
i have Gone through the code base of the controller and it can be re structured

```
public function store()
    {
        Auth::user()->account->users()->create(
            Request::validate([
                'first_name' => ['required', 'max:50'],
                'last_name' => ['required', 'max:50'],
                'email' => ['required', 'max:50', 'email', Rule::unique('users')],
                'password' => ['nullable'],
                'owner' => ['required', 'boolean'],
            ])
        );
        return Redirect::route('users')->with('success', 'User created.');
    }
```

So you dont need the Validation loging while creating the data you can just add the form request and isolate the validation login 

I have also found many code restructre like this

I am opening the issue because pingcrm is slowly getting populared  so it will be used in some of the entrprise companies

So app should be neat and  clean and must easy to maintain

So If You are intrested in Restructing the code kidly tell me i will create the PR for that

OR close the issue

**Comment by reinink** [comment]
Greetings @ManojKiranA! Thanks for your interest in Inertia.js and PingCRM.

While you absolutely could form request objects where I am currently doing validation inline, I actually prefer to *not* use them. I like having the validation directly in the controller. I also like that each post/put/patch endpoint doesn't require a corresponding form request file.

Thanks either way!
