### ISSUE TITLE
implementing a way to handle exceptions?

### ISSUE THREAD

**Issue by rakk7** [inertiajs/pingcrm#31]
A modal is shown whenever an exception happens in server side.. 

How would someone handle exceptions in Inertia? so that, it shows a vue's page instead of a modal?

It would be nice if this demo shows how to do that.

**Comment by reinink** [comment]
You would need to override your exception handling server-side to return an Inertia response. In a Laravel project that would be done in the [Exception/Handler](https://github.com/inertiajs/pingcrm/blob/master/app/Exceptions/Handler.php). If I get a chance I'll add that to this repo, but it likely won't be anytime soon unfortunately.

**Comment by sebastiandedeyne** [comment]
I started a discussion about this at https://github.com/inertiajs/inertia-laravel/issues/56

**Comment by reinink** [comment]
I've updated the new Inertia docs to include some recommendations on how to handle error handling in an Inertia/Laravel application. Find that [here](https://inertiajs.com/error-handling).
