### ISSUE TITLE
Position of Inertia middleware

### ISSUE THREAD

**Issue by sylarbg** [inertiajs/pingcrm#37]
Аccording to [documentation](https://github.com/inertiajs/inertia-laravel#add-inertia-middleware) 
Inertia\Middleware  it should be added "after any session related middleware", but in the example project is at the top of the stack ? Is this the right place or maybe after  [\Illuminate\View\Middleware\ShareErrorsFromSession::class](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L35) (in fresh laravel project)

**Comment by reinink** [comment]
Great catch! Fixed: 92321aeb1e099845609ddd248e4abc9ce1d56a8f

Reflashing of data on asset refreshing wasn't working in Ping CRM because of this.
