### ISSUE TITLE
navigation guard

### ISSUE THREAD

**Issue by donmbelembe** [inertiajs/pingcrm#38]
How to avoid going back to login page when user click back button

**Comment by donmbelembe** [comment]
This does not solve my case, after logout i'm still able to go back to home page.
Things like vue-router provide a way to tweek the navigator history via route middleware

**Comment by Juhlinus** [comment]
@donmbelembe See Jonathan's answer on my PR.

> It's worth noting that because of how Inertia works, if you click back you'll still see the login page, due to history state caching. This is standard browser behaviour.
> 
> However, if you visit the login page fresh again, you'll be redirected.



https://github.com/inertiajs/pingcrm/pull/39#issuecomment-521861246

**Comment by ellalderton** [comment]
If you use the application and then logout. If you click the back button you can still see the logged in state for the last page. Ideally this shouldn't show any authenticated pages and redirect you to the login page.

**Comment by adamwathan** [comment]
> If you click the back button you can still see the logged in state for the previous pages.

This is how traditional server rendered apps work too, try it right here on GitHub for example.

**Comment by ellalderton** [comment]
I was thinking more if there is away for the js/vue to check for the auth user and redirect.
