### ISSUE TITLE
Error in callback for immediate watcher

### ISSUE THREAD

**Issue by ergonomicus** [inertiajs/pingcrm#40]
I just followed the instructions to clone and install the application. Other pages seems to work fine, but all the page components that have `remember:` property set give me Vue warnings in console.

`[Vue warn]: Error in callback for immediate watcher "form": "TypeError: Cannot set property 'default' of undefined"`

This one is from Pages/Users/Edit.vue, and if I comment out `remember: 'form'` then error disappears. 

Anyone else gets this error/warning in console?

**Comment by Juhlinus** [comment]
Update your dependency so that you have the latest version of intertiajs(currently 0.1.3 as of writing this) and the error should go away.

**Comment by ergonomicus** [comment]
Yeah, that solved it. Thanks a lot!
