### ISSUE TITLE
Login Events

### ISSUE THREAD

**Issue by gregupton** [inertiajs/pingcrm#47]
In standard laravel apps I would log failed/successful login attempts via spatie/laravel-activitylog, but the login method used in pingcrm doesn't seem to trigger the events. 

```PHP
    /**
     * Handle the event.
     *
     * @param  Failed  $event
     * @return void
     */
    public function handle(Failed $event)
    {
        activity()->log(
            'Failed Login Attempt: ' . $event->credentials['email'] . ' IP:' . request()->ip()
        );
    }
```

```PHP

    /**
     * Handle the event.
     *
     * @param  Login  $event
     * @return void
     */
    public function handle(Login $event)
    {
        Activity()
        ->causedBy(Auth::getUser()->id)
        ->log(':causer.name logged in');
    }
```

```PHP
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        Failed::class => [
            \App\Listeners\LogFailedLoginAttempt::class,
        ],
        Login::class => [
            \App\Listeners\LogSuccessfulLogin::class,
        ],
    ];
```

**Comment by reinink** [comment]
Hey @gregupton, I am not really sure how that Spatie package works, so this question might be better asked with them. Inertia (and Ping CRM) doesn't really do anything special from an authorization perspective, other than return an Inertia view from the `LoginController`:

https://github.com/inertiajs/pingcrm/blob/75ae66a2c12ae4d704fdb4b0378fb2493d4e1943/app/Http/Controllers/Auth/LoginController.php#L36-L39

Sorry I cannot be more helpful.
