### ISSUE TITLE
Search on input select

### ISSUE THREAD

**Issue by fellipesac** [inertiajs/pingcrm#51]
Hey! How i search on input select with tailwind?? Thx so much

**Comment by reinink** [comment]
Hey, I'm sorry, but I'm not really sure what you're asking. Please provide more information.

**Comment by fellipesac** [comment]
![image](https://user-images.githubusercontent.com/16749703/67520140-a8cf9780-f67e-11e9-8216-118620c30fba.png)

u did it on another project
can u share to apply?

**Comment by reinink** [comment]
I'm sorry, but I don't have an open-source version of that custom component available.

**Comment by wadday** [comment]
> ![image](https://user-images.githubusercontent.com/16749703/67520140-a8cf9780-f67e-11e9-8216-118620c30fba.png)
> 
> u did it on another project
> can u share to apply?

Check this out.
https://vue.ant.design/components/auto-complete/
