### ISSUE TITLE
scroll-region??

### ISSUE THREAD

**Issue by roni-estein** [inertiajs/pingcrm#53]
I noticed this in a div on Layout.vue now that I have time to GROK this project.

```
<div class="w-full overflow-hidden px-4 py-8 md:p-12 overflow-y-auto" scroll-region>
    <flash-messages />
    <slot />
</div>
```

I can't even find scroll-region on google!!!

Where did you find this? Can you leave a brief message on what it does?

I've removed it and I can't figure out the difference.

Cheers and thanks

**Comment by imsus** [comment]
https://inertiajs.com/pages#scroll-regions

> When navigating between pages, Inertia will automatically reset the scroll position to the top of the body (unless disabled via the preserve-scroll functionality).

> Depending on your app, you may have nested scroll containers within your layout, and these will not be reset by default. You can tell Inertia to also reset these areas by adding a scroll-region attribute.

**Comment by roni-estein** [comment]
Thank you! I thought I had gone through the docs start to finish.
