### ISSUE TITLE
Support for Sorting Column

### ISSUE THREAD

**Issue by ManojKiranA** [inertiajs/pingcrm#58]
It would be great if sorting of Columns is added to list

**Comment by leocharrua** [comment]
Hello, I'm in a project Laravel Inertia with vuejs. How I can get the sort function in the table columns? Any ideas? Any vue table component that works with inertia?
Thanks

**Comment by ordago** [comment]
@ManojKiranA , @leocharrua 

These might help

https://github.com/protonemedia/inertiajs-tables-laravel-query-builder

https://www.youtube.com/watch?v=8vBw_QmKf3c

**Comment by mchev** [comment]
#167

**Comment by driesvints** [comment]
We're open to PR's, thanks.
