### ISSUE TITLE
Possible Example for Deleting Images?

### ISSUE THREAD

**Issue by marbuser** [inertiajs/pingcrm#59]
So I'm referencing the example given inside Users to creating and updating images, but I noticed it doesn't really show how to do deleting of images?

I've tried to implement something myself but given the limitations of FormData, I'm not entirely sure the best way to approach it. It would be cool to see an example that shows up uploads of multiple files as well.

Since the problem I've got at the moment is trying to somehow differentiate what files have/haven't been changed. Because currently my form just resubmits ALL images no matter what, even if you just change a text field which isn't great for bandwidth and really slows down the app especially if you are uploading say 10 image files.

I think this will be a good overall example to include as well since it seems like a fair amount of people ask about this on various different places.

Hopefully you can add it!

**Comment by lostdesign** [comment]
@marbuser Can you share on how you tried to do this? It's easier then to understand where the issue is. Once that's resolved you could open a PR for this - I am happy to help with that.

**Comment by ed-mor** [comment]
use Illuminate\Support\Facades\Storage;
Storage::delete($imgOld);

**Comment by barnoma-soz** [comment]
I would like to hear the opinions of other developers. Is it correct to do this to delete the previous photo

```php
// app/Models/User.php

protected static function booted()
{
    static::saving(function ($user) {
        if ($user->isDirty('photo_path')) {
            // Delete previous image
            if (Storage::exists($user->getOriginal('photo_path'))) {
                Storage::delete($user->getOriginal('photo_path'));
            }
        }
    });
}
```

**Comment by lostdesign** [comment]
I'd rather explicitly call it on the controller or inside an action to be honest. That way it would not be called everytime and you may need to add the new image anyways. Let's say you are just letting update the name or email for example, for each and every save you'd still check wether the image has changed and that causes some I/O on your disk. 

At scale it may be a bit too much. 

If you anyways save everything every time the user changes their profile, well sure why not? 

Maybe look into spatie/media-library, they got such functionality.

Another solution could be to have a folder for their avatar per user and simply overwriting the path with the same filename which would get rid of the old image as well.

**Comment by driesvints** [comment]
No plans for this right now, sorry.
