### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by ryanmortier** [inertiajs/pingcrm#6]
Is there a reason this is locked to PHP 7.2 and won't install with PHP 7.3?

**Comment by reinink** [comment]
Nope! Only because Ping was based on a client project, which is hosted on Heroku, where I had specific PHP version set. I'll fix this.

**Comment by reinink** [comment]
Done: 2b07069030eeebf1b4f2cffcd869a3803ae668f8

**Comment by ryanmortier** [comment]
Cool thanks!
