### ISSUE TITLE
Search / Axios config

### ISSUE THREAD

**Issue by roni-estein** [inertiajs/pingcrm#60]
Hey, I have something that appears quite trivial in regular vue / laravel that's stumping me.

I have a search field bound to a data element search. I need to use an omnibox style search, which is all set up and tested on laravel and returns a list of objects.

When using inertia post, it gets the correct data but attempts to go to the route. It ends up sending back modal with [Object, Object]. The response looks fine, but I need that array mapped back to my computed property or some variable. However my then or catch keys are never activated.

I tried replacing it with a simple axios.post, but I'm stuck with CSRF mismatch. Is there a config I can use for CSRF token when using an axios request in inertia? Or is there a better way to get data back and populate my list.

Thanks

**Comment by roni-estein** [comment]
Yikes, I dug around a bit and found the solution here
https://github.com/inertiajs/inertia-vue/issues/39#issuecomment-494425358

thanks for the .url() tip.
ZIGGY!!!!

**Comment by reinink** [comment]
Glad you got it figured out. 👍

**Comment by chrisgrim** [comment]
That link is dead and I am having the same issue. Is there a different place to check it out?
