### ISSUE TITLE
More Icons in Icons.vue component

### ISSUE THREAD

**Issue by viraljetani** [inertiajs/pingcrm#67]
Any way we can add more icons in the Icons.vue component? Would like to add some more icons that can be used in the application.

**Comment by rdrubis** [comment]
> Any way we can add more icons in the Icons.vue component? Would like to add some more icons that can be used in the application.

Hey @viraljetani, you can add more SVG icons to the Icon.vue component by simply pasting in the SVG code and inserting "v-else-if" Vue directive and assign a name like so:

`<svg v-else-if="name === 'icon-name'" ... </svg>`

You can grab SVG icons from [zondicons.com](https://www.zondicons.com/), [heroicons.dev](https://heroicons.dev/), or any other sources.

Here is an example of adding the airplane icon from [zondicons.com](https://www.zondicons.com/):

`<svg v-else-if="name === 'airplane'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M8.4 12H2.8L1 15H0V5h1l1.8 3h5.6L6 0h2l4.8 8H18a2 2 0 1 1 0 4h-5.2L8 20H6l2.4-8z"/></svg>`

You can then use the newly added icon in any of your Vue single file components that imports the Icon component like so:

`<icon name="airplane" ... />`

I hope this helps!

**Comment by Juhlinus** [comment]
Great answer @rdrubis!

Do you feel like the answer resolved your issue, @viraljetani?

**Comment by reinink** [comment]
Thanks for answering this @rdrubis! That's exactly right. The `Icon.vue` component isn't intended to provide a complete set of possible icons, but rather represent a pattern that I use to organize my icons. Feel free to edit that component with more icons as needed. 👍
