### ISSUE TITLE
this.$inertia.put not working. Laravel update method does not getting model and request data

### ISSUE THREAD

**Issue by santlalgodara** [inertiajs/pingcrm#69]
this.$inertia.put(this.route('users.update', this.user.id), formData).then(() => {
          this.sending = false
})

Laravel :
    public function update(Request $request, User $user)
    {
        return  $request->all(); // $request->name // $user 
}

did not get any data to request or $user model...

Form Data sending to the exact route
![image](https://user-images.githubusercontent.com/17198268/83509784-9c030400-a4e9-11ea-84a3-35480a9f1364.png)

response from update method 
![image](https://user-images.githubusercontent.com/17198268/83509823-ab824d00-a4e9-11ea-8673-9190a07b870d.png)

***Store method working fine. I am sending data exact same way  ****

**Comment by sebastiandedeyne** [comment]
What does `formData` look like? Where is it populated?

I think this is something related to the browser sending a FormData object instead of JSON (not sure, just a hunch)

**Comment by santlalgodara** [comment]
submit method >>>

           var formData = new FormData();
            formData.append("name", this.form.name || "");
            formData.append("email", this.form.email || "");
            formData.append("password", this.form.password || "");
            formData.append("password_confirmation", this.form.passwordConfirmation || "");
            formData.append("status", this.form.status || false);
            formData.append("phoneNo", this.form.phoneNo || "");
            formData.append("role", this.form.role || null);
            formData.append("profilePhoto", this.form.profilePhoto || "");
            this.$inertia.put(this.route('users.update', this.user.id), formData)
                .then(() => {
                this.sending = false
                })

**Comment by santlalgodara** [comment]
> submit method >>>
> 
> ```
>        var formData = new FormData();
>         formData.append("name", this.form.name || "");
>         formData.append("email", this.form.email || "");
>         formData.append("password", this.form.password || "");
>         formData.append("password_confirmation", this.form.passwordConfirmation || "");
>         formData.append("status", this.form.status || false);
>         formData.append("phoneNo", this.form.phoneNo || "");
>         formData.append("role", this.form.role || null);
>         formData.append("profilePhoto", this.form.profilePhoto || "");
>         this.$inertia.put(this.route('users.update', this.user.id), formData)
>             .then(() => {
>             this.sending = false
>             })
> ```

And the same for store method and that's working as expected.

**Comment by Juhlinus** [comment]
Append a method field to the formData and send a post request instead and it should be fine.

Check how it's done in PingCRM below.

https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L86-L95

**Comment by sebastiandedeyne** [comment]
What @Juhlinus said!

Fyi, here's the underlying issue: https://github.com/laravel/framework/issues/13457

**Comment by devtech92** [comment]
> Append a `_method` field to the formData and send a post request instead and it should be fine.
> 
> Check how it's done in PingCRM below.
> 
> https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L86-L95

Thank you very much. I had same issue but that worked for me.

**Comment by wardvisual** [comment]
> Append a `_method` field to the formData and send a post request instead and it should be fine.
> 
> Check how it's done in PingCRM below.
> 
> https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L86-L95

Thanks!
