### ISSUE TITLE
Undefined variable: fail (in Demo)

### ISSUE THREAD

**Issue by whoami15** [inertiajs/pingcrm#74]
There's an error in **Error 500** page
[Link](https://demo.inertiajs.com/500)

_**Undefined variable: fail**_

Code:
```php
Route::get('500', function () {

    // Force debug mode for this endpoint in the demo environment

    if (App::environment('demo')) {

        Config::set('app.debug', true);

    }

    echo $fail;

});
```

**Comment by Juhlinus** [comment]
> There's an error in **Error 500** page
> [Link](https://demo.inertiajs.com/500)
> 
> _**Undefined variable: fail**_
> 
> Code:
> 
> ```
> Route::get('500', function () {
> 
>     // Force debug mode for this endpoint in the demo environment
> 
>     if (App::environment('demo')) {
> 
>         Config::set('app.debug', true);
> 
>     }
> 
>     echo $fail;
> 
> });
> ```

Hello @whoami15 !

That is correct! That is the intended result, in order to show what a 500 error looks like.

**Comment by reinink** [comment]
<img width="1074" alt="Screen Shot 2020-07-29 at 9 48 58 AM" src="https://user-images.githubusercontent.com/882133/88808420-dce16700-d180-11ea-8a39-66eadf25a57f.png">

Added (73d294f2dcc8d61a8ae666165f42756a8dc4b7ac) a little note to the dashboard to make this a little more clear. 👌

**Comment by whoami15** [comment]
> <img alt="Screen Shot 2020-07-29 at 9 48 58 AM" width="1074" src="https://user-images.githubusercontent.com/882133/88808420-dce16700-d180-11ea-8a39-66eadf25a57f.png">
> 
> Added ([73d294f](https://github.com/inertiajs/pingcrm/commit/73d294f2dcc8d61a8ae666165f42756a8dc4b7ac)) a little note to the dashboard to make this a little more clear. 👌

Thank you Jonathan 👍
