### ISSUE TITLE
List of all app route in source code

### ISSUE THREAD

**Issue by inlogicstudio** [inertiajs/pingcrm#89]
When the app source code is view in the browser the list of all route in the application can be seen which I think this is insecured  if there is other reason for this please kindly state
![Screenshot_20201021-090116](https://user-images.githubusercontent.com/55183401/96690825-138fdd80-137c-11eb-84ec-d5756aaf592d.jpg)

**Comment by reinink** [comment]
This is because Ping CRM uses the [Ziggy](https://github.com/tighten/ziggy) library to share server-side routes with the client-side. See that project for more info. 👍
