### ISSUE TITLE
Any update to Vue3?

### ISSUE THREAD

**Issue by stonkeep** [inertiajs/pingcrm#90]
Any update to Vue3?

**Comment by regisaih** [comment]
+1

**Comment by ThisIsntMyId** [comment]
+1

**Comment by reinink** [comment]
While I'd like to eventually update this project to Vue 3, Vue 2 is still the default version that Vue installs when you run `npm install vue`, so until the team has decided that Vue 3 is 100% ready and has replaced Vue 2 as the recommended version, I’m not going to prioritize this.
