### ISSUE TITLE
Tailwind 2.0 support

### ISSUE THREAD

**Issue by ricardohs35** [inertiajs/pingcrm#94]
Are there any plans to upgrade Tailwindcss? I was looking to use the `Tailwind UI` components, but some of them require Tailwind 2.0

**Comment by regisaih** [comment]
+1

**Comment by Landish** [comment]
@ricardohs35  @regisaih 

If you'll find this helpful, I've updated my [pingcrm-react](https://github.com/Landish/pingcrm-react) repo to use Tailwind 2 and even Laravel Mix 6.

**Comment by reinink** [comment]
This has been added to upcoming update: #99
