### ISSUE TITLE
Browser Back Button 

### ISSUE THREAD

**Issue by anisur3036** [inertiajs/pingcrm#96]
I am new at Inertiajs. It might be my problem not inertiajs issue. Anyway...

After successfully login, when I click browser back button I am showing my login page again. How can I protect viewing login page after successfully login. Thanks

**Comment by sebastiandedeyne** [comment]
You could do this by checking if the user is logged in in the `created` hook (using Vue) of the login page. This could be by doing an HTTP call, checking a cookie…

**However,** Inertia is built to have applications behave the way browsers intend them to. The back button should restore the state of the page that the user saw last, regardless of it being stale.
