### ISSUE TITLE
Need help to understand

### ISSUE THREAD

**Issue by swapnilnandgave** [inertiajs/pingcrm#97]
I am new to inertia and vuejs and trying to understand code written for demo. Below is dashboard page code. I wanted to understand how does it reflect with top and left navigation bar as it is not included in code

`<template>
  <div>
    <h1 class="mb-8 font-bold text-3xl">Dashboard</h1>
    <p class="mb-8 leading-normal">Hey there! Welcome to Ping CRM, a demo app designed to help illustrate how <a class="text-indigo-500 underline hover:text-orange-600" href="https://inertiajs.com">Inertia.js</a> works.</p>
    <div class="mb-8 flex">
      <inertia-link class="btn-indigo" href="/500">500 error</inertia-link>
      <inertia-link class="btn-indigo ml-1" href="/404">404 error</inertia-link>
    </div>
    <p class="leading-normal">👆 These links are intended to be broken to illustrate how error handling works with Inertia.js.</p>
  </div>
</template>

<script>
import Layout from '@/Shared/Layout'

export default {
  metaInfo: { title: 'Dashboard' },
  layout: Layout,
}
</script>
`

**Comment by reinink** [comment]
Hey there!

The layout is added via the layout property:

```js
import Layout from '@/Shared/Layout'
// ...
layout: Layout,
```

This feature is called persistent layouts, which you can read more about here: https://inertiajs.com/pages#persistent-layouts

Hope that helps 👍

**Comment by swapnilnandgave** [comment]
Very well explained.. Thanks
